### PR TITLE
Added Python section.

### PR DESCRIPTION
**Pull request by Vikirnt**
Added a few tutorials for Python through which I'm learning the language.

### CODE REVIEW

**Comment by rpanchal1996** [comment]
Add a new section for "Programming Languages". Add python as a subsection there.

**Comment by Vikirnt** [comment]
How about separation of frameworks and languages?

**Comment by AvaisP** [comment]
What are you suggesting?

**Comment by Vikirnt** [comment]
In the web section: HTML, CSS, and Javascript are mixed with their frameworks/ libraries - Bootstap, AJAX, jQuery.

Most of the FEs would have to learn the languages first and then the frameworks. So I'm suggesting to re-order the sections.

Anyways - I moved the language guides for Javascript to the top and moved Python into "Language" section.

**Pull request merged**
