### PR TITLE
Merge pull request #1 from djunicode/master

### PR DESCRIPTION
**Pull request by Nikesh2712**
Front end resources

### CODE REVIEW

**Comment by AvaisP** [comment]
@Nikesh2712 
What exactly is this PR doing? It doesn't change any files

**Comment by Nikesh2712** [comment]
Oh ya I sent this PR By mistake. I have sent another PR for committing changes to README file

**Comment by AvaisP** [comment]
Don't send another PR
Just commit to the master branch of your fork. It'll get added here

**Comment by AvaisP** [comment]
@Nikesh2712 ?

**Comment by rpanchal1996** [comment]
duplicate

**Pull request closed without merging**
